name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            java-package: jdk
      - name: Decrypt Keys
        run: |
          openssl aes-256-cbc -pass pass:${{ secrets.ENCRYPTION_PASSWORD }} -in deploy/pubring.gpg.enc -out deploy/pubring.gpg -d
          openssl aes-256-cbc -pass pass:${{ secrets.ENCRYPTION_PASSWORD }} -in deploy/secring.gpg.enc -out deploy/secring.gpg -d
      - name: Maven Release
        run: mvn deploy --settings deploy/settings.xml -DperformRelease=true -DskipTests=true
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
